server:
  port: 8088
  servlet:
    context-path: /testcrud
spring:
  application:
    name: testcrud
  config:
    import: configserver:http://localhost:8888
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/testcrudproject
    username: root
    password: root
  jpa:
    show-sql: true
    properties:
      hibernate.format_sql: true
      hibernate.ddl-auto: create
      hibernate.dialect: org.hibernate.dialect.MariaDBDialect
      hibernate.current_session_context_class: org.springframework.orm.hibernate5.SpringSessionContext   
