server:
  port: 8083
  servlet:
    context-path: /ORS10
spring:
  application:
    name: ORS10
  config:
    import: configserver:http://localhost:8888
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/ors_p10
    username: root
    password: root
  jpa:
    show-sql: true
    properties:
      hibernate.format_sql: true
      hibernate.ddl-auto: update
      hibernate.dialect: org.hibernate.dialect.MariaDBDialect
      hibernate.current_session_context_class: org.springframework.orm.hibernate5.SpringSessionContext   
